services:
  _defaults:
    public: true

  ExEss\Cms\Component\Flow\Action\BackendCommandExecutor:
    arguments:
      - !tagged { tag: 'backend.command', index_by: 'alias' }

  ExEss\Cms\CRUD\BackendCommand\CrudDeleteRelationshipCommand:
    autowire: true
    tags: [{ name: 'backend.command', alias: 'crudDeleteRelationship' }]

