# At the moment these commands are public since we're calling them directly,
# but at some point in time we should be able to all make them private
services:
  _defaults:
    autowire: true

  # General CRM commands
  ExEss\Bundle\CmsBundle\Command\AbstractAdminCommand:
    abstract: true
    calls:
      - login: ['@security.token_storage', '@ExEss\Bundle\CmsBundle\Api\V8_Custom\Service\User\DefaultUser']

  ExEss\Bundle\CmsBundle\Command\:
    public: true
    autowire: true
    parent: ExEss\Bundle\CmsBundle\Command\AbstractAdminCommand
    resource: '../../src/ExEss/Bundle/CmsBundle/Command'
    tags: ['console.command']

  ExEss\Bundle\CmsBundle\Component\PhpCS\Command\:
    public: true
    autowire: true
    resource: '../../src/ExEss/Bundle/CmsBundle/Component/PhpCS/Command'
    tags: ['console.command']
