services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  ExEss\Cms\Http\ParamConverter\BaseEntityConverter: ~

  # Controller middleware

  ExEss\Cms\Api\V8_Custom\Controller\ParamConverter\ParamObjectConverter: ~

  # Controller middleware converter factories

  ExEss\Cms\Api\V8_Custom\Controller\ParamConverter\ParamObjectConverterFactory:
    arguments:
      - '@service_container'

