services:
  _defaults:
    public: true


  # Controller middleware

  ExEss\Cms\Api\V8_Custom\Controller\ParamConverter\ParamObjectConverter: ~

  # Controller middleware converter factories

  ExEss\Cms\Api\V8_Custom\Controller\ParamConverter\ParamObjectConverterFactory:
    arguments:
      - '@service_container'

  ExEss\Cms\Api\V8_Custom\Controller\ParamConverter\RequestConverterFactory: ~

