services:
  _defaults:
    public: true

  ExEss\Cms\Component\Health\HealthCheckService:
    arguments:
      - !tagged { tag: 'handler.health', index_by: 'alias' }

  # Handlers
  ExEss\Cms\Component\Health\Handler\DoctrineHandler:
    arguments:
      - '@doctrine.dbal.default_connection'
    tags: [{ name: 'handler.health', alias: 'database' }]
