services:
  _defaults:
    public: true

  ExEss\Cms\Component\Health\HealthService:
    arguments:
      - !tagged { tag: 'handler.health', index_by: 'alias' }
      - '@Symfony\Component\Serializer\Serializer'

  # Handlers
  ExEss\Cms\Component\Health\Handler\DoctrineHandler:
    arguments:
      - '@doctrine.dbal.default_connection'
    tags: [{ name: 'handler.health', alias: 'database' }]
