parameters:
  app_secret: '%env(string:APP_SECRET)%'
  api_token_timeout: 3600
  api_token_refresh: 1800

services:
  _defaults:
    public: true

  ExEss\Cms\Api\V8_Custom\Service\User\RefreshTokenService:
    arguments:
      - '%api_token_timeout%'
      - '%api_token_refresh%'
      - '%app_secret%'
