services:
  _defaults:
    public: true

  # V8_Custom routeparams
  ExEss\Cms\Api\V8_Custom\Params\FlowUpdateParams:
    arguments:
      - '@ExEss\Cms\Api\V8_Custom\Params\Validator\ValidatorFactory'
      - '@ExEss\Cms\Cleaner\HtmlCleaner'
      - '@doctrine.orm.entity_manager'
