services:
  _defaults:
    public: true

  # V8_Custom routeparams
  ExEss\Cms\Api\V8_Custom\Params\ActionParams:
    arguments:
      - '@ExEss\Cms\Api\V8_Custom\Params\Validator\ValidatorFactory'
      - '@doctrine.orm.entity_manager'

  ExEss\Cms\Api\V8_Custom\Params\GetFilterParams:
    arguments:
      - '@ExEss\Cms\Api\V8_Custom\Params\Validator\ValidatorFactory'
      - '@doctrine.orm.entity_manager'

  ExEss\Cms\Api\V8_Custom\Params\FlowUpdateParams:
    arguments:
      - '@ExEss\Cms\Api\V8_Custom\Params\Validator\ValidatorFactory'
      - '@ExEss\Cms\Cleaner\HtmlCleaner'
      - '@doctrine.orm.entity_manager'

  ExEss\Cms\Api\V8_Custom\Params\ListRowbarParams:
    arguments:
      - '@ExEss\Cms\Api\V8_Custom\Params\Validator\ValidatorFactory'
      - '@ExEss\Cms\Service\GridService'

  ExEss\Cms\Api\V8_Custom\Params\ListRowbarActionParams:
    arguments:
      - '@ExEss\Cms\Api\V8_Custom\Params\Validator\ValidatorFactory'

  ExEss\Cms\Api\V8_Custom\Params\SelectWithSearchParams:
    arguments:
      - '@ExEss\Cms\Api\V8_Custom\Params\Validator\ValidatorFactory'
