parameters:
  app_secret: '%env(string:APP_SECRET)%'
  api_token_timeout: 3600

services:
  _defaults:
    public: true
    autowire: true

  ExEss\Cms\Api\V8_Custom\Service\User\TokenService:
    bind:
      $timeout: '%api_token_timeout%'
      $secret: '%app_secret%'

  ExEss\Cms\Security\JsonLoginAuthenticator: ~

  ExEss\Cms\Security\JwtTokenAuthenticator: ~

  ExEss\Cms\Security\Listener\LogoutSuccessSubscriber:
    tags:
      - name: kernel.event_subscriber
        dispatcher: security.event_dispatcher.api

  ExEss\Cms\Api\V8_Custom\Service\User\DefaultUser: ~

  ExEss\Cms\Acl\AclService: ~

  ExEss\Cms\Users\Security\DecisionManager:
    bind:
      $voters: !tagged_iterator user.voter

  ExEss\Cms\Security\Route\DecisionManager:
    bind:
      $voters: !tagged_iterator route.voter

  # Route voters

  ExEss\Cms\Security\Route\Voter\RouteVoter:
    arguments:
      - '@ExEss\Cms\Api\V8_Custom\Service\Security'
      - '@ExEss\Cms\SecurityGroups\SecurityGroupsRepository'
    tags: ['route.voter']

  # CRUD
  ExEss\Cms\CRUD\Helpers\SecurityService:
    arguments:
      - '@ExEss\Cms\Api\V8_Custom\Service\Security'
