# Slim parameters
parameters:
  httpVersion: '1.1'
  routerCacheFile: '%kernel.cache_dir%/routes.php'
  displayErrorDetails: true
  slimSettings:
    httpVersion: '%httpVersion%'
    responseChunkSize: 4096
    outputBuffering: 'append'
    determineRouteBeforeAppMiddleware: true
    displayErrorDetails: '%displayErrorDetails%'
    addContentLengthHeader: true
    routerCacheFile: '%routerCacheFile%'

# Default slim services
services:
  _defaults:
    public: true

  settings:
    class: Slim\Collection
    arguments:
      - '%slimSettings%'

  ExEss\Cms\Factory\EnvironmentFactory: ~

  environment:
    class: Slim\Http\Environment
    factory: ['@ExEss\Cms\Factory\EnvironmentFactory', create]

  Slim\Http\Request:
    class: Slim\Http\Request
    factory: [Slim\Http\Request, createFromEnvironment]
    arguments:
      - '@environment'

  request: '@Slim\Http\Request'

  Slim\Http\Response:
    class: Slim\Http\Response
    arguments:
      - 200
      - '@response.headers'
    calls:
      - [withProtocolVersion, ['%httpVersion%']]

  response: '@Slim\Http\Response'

  Slim\Http\Headers:
    class: Slim\Http\Headers
    arguments:
      -
        Content-Type: 'text/html; charset=UTF-8'

  response.headers: '@Slim\Http\Headers'

  Slim\Router:
    class: Slim\Router
    calls:
      - ['setCacheFile', ['%routerCacheFile%']]
      - ['setContainer', ['@service_container']]

  foundHandler:
    class: ExEss\Cms\Api\V8_Custom\Controller\InvocationStrategy\ParamsInvocationStrategy

  phpErrorHandler:
    class: Slim\Handlers\PhpError
    arguments:
      - '%displayErrorDetails%'

  errorHandler:
    class: Slim\Handlers\Error
    arguments:
      - '%displayErrorDetails%'

  notFoundHandler:
    class: Slim\Handlers\NotFound

  notAllowedHandler:
    class: Slim\Handlers\NotAllowed

  callableResolver:
    class: Slim\CallableResolver
    arguments:
      - '@service_container'

  ExEss\Cms\Http\Cookies:
    arguments:
      - '@=service("request").getCookieParams()'
    calls:
      - setDefaults:
          -
            secure: '@=service("ExEss\\Cms\\Factory\\EnvironmentFactory").isSSL()'
            httponly: true
            path: "/"

  cookie: '@ExEss\Cms\Http\Cookies'