services:
  _defaults:
    public: true

  ExEss\Cms\Component\Flow\Suggestions\DynamicEnumHandler:
    lazy: true
    arguments:
      - '@ExEss\Cms\Component\Flow\EnumRecordFactory'
      - '@ExEss\Cms\Component\Flow\Builder\EnumFieldBuilder'
    tags:
      - { name: 'suggestions', priority: 750 }

  ExEss\Cms\Component\Flow\Suggestions\DefaultValueHandler:
    lazy: true
    arguments:
      - '@ExEss\Cms\Component\Flow\DefaultValueService'
    tags:
      - { name: 'suggestions', priority: 620 }

  ExEss\Cms\Component\Flow\Suggestions\AutoSelectSuggestionHandler:
    lazy: true
    arguments:
      - '@doctrine.orm.entity_manager'
    tags:
      - { name: 'suggestions', priority: 110 } # one last time

  ExEss\Cms\Component\Flow\Suggestions\IbanFormatterSuggestionHandler:
    lazy: true
    arguments:
      - '@ExEss\Cms\FieldFormatter\IbanFormatter'
    tags:
      - { name: 'suggestions', priority: 270 }
      - { name: 'pre-validation-suggestion', priority:  130 }       # Format IBAN on confirm

  ExEss\Cms\Component\Flow\Suggestions\AutoExpandSelectWithSearch:
    lazy: true
    arguments:
      - '@ExEss\Cms\Service\SelectWithSearchService'
    tags:
      - { name: 'suggestions', priority: 200 }

  ExEss\Cms\Component\Flow\Suggestions\AutoSelectWithSearchSuggestionHandler:
    lazy: true
    arguments:
      - '@ExEss\Cms\Service\SelectWithSearchService'
    tags:
      - { name: 'suggestions', priority:  100 }

  ExEss\Cms\CRUD\Suggestions\RecordFieldSuggestion:
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@ExEss\Cms\CRUD\Factory\FieldFactory'
      - '@ExEss\Cms\CRUD\Helpers\SecurityService'
    tags:
      - { name: 'suggestions', priority:  50 }

  ExEss\Cms\CRUD\Suggestions\RecordTypeSuggestion:
    lazy: true
    tags:
      - { name: 'suggestions', priority: 20 }

  ExEss\Cms\CRUD\Suggestions\RecordRelationSuggestion:
    lazy: true
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@ExEss\Cms\CRUD\Helpers\SecurityService'
    tags:
      - { name: 'suggestions', priority:  10 }

  ExEss\Cms\Component\Flow\Suggestions\SelectWithSearchLabelHandler:
    lazy: true
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@ExEss\Cms\Service\SelectWithSearchService'
    tags:
      - { name: 'suggestions', priority: -1 }

  ### PRE VALIDATION SUGGESTIONS

  ExEss\Cms\Component\Flow\Suggestions\OverrideDefaultHandler:
    lazy: true
    arguments:
      - '@ExEss\Cms\Component\Flow\Field'
      - '@ExEss\Bundle\CmsBundle\Component\ExpressionParser\ParserService'
    tags:
      - { name: 'pre-validation-suggestion', priority:  330 } # Should go first, can update the model

  ExEss\Cms\Component\Flow\Suggestions\FieldFormattingHandler:
    lazy: true
    arguments:
      - '@ExEss\Cms\FieldFormatter\VatNumberFormatter'
      - '@ExEss\Cms\FieldFormatter\PhoneNumberFormatter'
    tags:
      - { name: 'pre-validation-suggestion', priority:  300 }

  ExEss\Cms\CRUD\Factory\FieldFactory:
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@ExEss\Cms\Component\Flow\EnumRecordFactory'
      - '@ExEss\Cms\Service\SelectWithSearchService'
