parameters:
  env(TRANSLATOR_CACHE): true
  env(TRANSLATOR_UNTRANSLATED_DATABASE): false

  default_locale: nl_BE
  business_default_language: nl_BE
  translator_cache: '%env(bool:TRANSLATOR_CACHE)%'
  translator_untranslated_database: '%env(bool:TRANSLATOR_UNTRANSLATED_DATABASE)%'

services:
  _defaults:
    public: true

  ExEss\Cms\Factory\TranslatorFactory:
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@=service(constant("ExEss\\Bundle\\CmsBundle\\Component\\Cache\\Dictionary::TRANSLATION"))'
      - '@ExEss\Cms\Api\V8_Custom\Translator\DatabaseLoader'
      - '@ExEss\Cms\Api\V8_Custom\Service\Security'

  Symfony\Component\Translation\Translator:
    lazy: true
    class: ExEss\Cms\Api\V8_Custom\Translator\LoggedTranslator
    factory: [ '@ExEss\Cms\Factory\TranslatorFactory', create ]
    arguments:
      - '%translator_untranslated_database%'
      - '%translator_cache%'
      - '%default_locale%'
  Symfony\Contracts\Translation\TranslatorInterface: '@Symfony\Component\Translation\Translator'

  ExEss\Cms\Api\V8_Custom\Translator\DatabaseLoader:
    arguments:
      - '@doctrine.orm.entity_manager'
