parameters:
  default_country_code: 'BE'
  constraints:
    # Custom constraints
    FixedPhoneNumber: ExEss\Cms\Validators\FixedPhoneNumber
    InList: ExEss\Cms\Validators\InList
    IsEndOfMonth: ExEss\Cms\Validators\IsEndOfMonth
    MobilePhoneNumber: ExEss\Cms\Validators\MobilePhoneNumber
    NotInList: ExEss\Cms\Validators\NotInList
    MultiEmail: ExEss\Cms\Validators\MultiEmail
    PhoneNumber: ExEss\Cms\Validators\PhoneNumber
    UserId: ExEss\Cms\Validators\UserId
    Vat: ExEss\Cms\Validators\Vat

    # Symfony constraints
    All: Symfony\Component\Validator\Constraints\All
    Bic: Symfony\Component\Validator\Constraints\Bic
    Blank: Symfony\Component\Validator\Constraints\Blank
    Callback: Symfony\Component\Validator\Constraints\Callback
    CardScheme: Symfony\Component\Validator\Constraints\CardScheme
    Choice: Symfony\Component\Validator\Constraints\Choice
    Collection: Symfony\Component\Validator\Constraints\Collection
    Composite: Symfony\Component\Validator\Constraints\Composite
    Count: Symfony\Component\Validator\Constraints\Count
    Country: Symfony\Component\Validator\Constraints\Country
    Currency: Symfony\Component\Validator\Constraints\Currency
    Date: Symfony\Component\Validator\Constraints\Date
    DateTime: Symfony\Component\Validator\Constraints\DateTime
    Email: Symfony\Component\Validator\Constraints\Email
    EqualTo: Symfony\Component\Validator\Constraints\EqualTo
    Existence: Symfony\Component\Validator\Constraints\Existence
    Expression: Symfony\Component\Validator\Constraints\Expression
    File: Symfony\Component\Validator\Constraints\File
    GreaterThanOrEqual: Symfony\Component\Validator\Constraints\GreaterThanOrEqual
    GreaterThan: Symfony\Component\Validator\Constraints\GreaterThan
    Iban: Symfony\Component\Validator\Constraints\Iban
    IdenticalTo: Symfony\Component\Validator\Constraints\IdenticalTo
    Image: Symfony\Component\Validator\Constraints\Image
    Ip: Symfony\Component\Validator\Constraints\Ip
    Isbn: Symfony\Component\Validator\Constraints\Isbn
    IsFalse: Symfony\Component\Validator\Constraints\IsFalse
    IsNull: Symfony\Component\Validator\Constraints\IsNull
    Issn: Symfony\Component\Validator\Constraints\Issn
    IsTrue: Symfony\Component\Validator\Constraints\IsTrue
    Language: Symfony\Component\Validator\Constraints\Language
    Length: Symfony\Component\Validator\Constraints\Length
    LessThanOrEqual: Symfony\Component\Validator\Constraints\LessThanOrEqual
    LessThan: Symfony\Component\Validator\Constraints\LessThan
    Locale: Symfony\Component\Validator\Constraints\Locale
    Luhn: Symfony\Component\Validator\Constraints\Luhn
    NotBlank: Symfony\Component\Validator\Constraints\NotBlank
    NotEqualTo: Symfony\Component\Validator\Constraints\NotEqualTo
    NotIdenticalTo: Symfony\Component\Validator\Constraints\NotIdenticalTo
    NotNull: Symfony\Component\Validator\Constraints\NotNull
    Optional: Symfony\Component\Validator\Constraints\Optional
    Range: Symfony\Component\Validator\Constraints\Range
    Regex: Symfony\Component\Validator\Constraints\Regex
    Required: Symfony\Component\Validator\Constraints\Required
    Time: Symfony\Component\Validator\Constraints\Time
    Traverse: Symfony\Component\Validator\Constraints\Traverse
    Type: Symfony\Component\Validator\Constraints\Type
    Url: Symfony\Component\Validator\Constraints\Url
    Uuid: Symfony\Component\Validator\Constraints\Uuid
    Valid: Symfony\Component\Validator\Constraints\Valid

  validators:
    - ExEss\Cms\Validators\FixedPhoneNumberValidator
    - ExEss\Cms\Validators\InListValidator
    - ExEss\Cms\Validators\IsEndOfMonthValidator
    - ExEss\Cms\Validators\MobilePhoneNumberValidator
    - ExEss\Cms\Validators\MultiEmailValidator
    - ExEss\Cms\Validators\NotInListValidator
    - ExEss\Cms\Validators\PhoneNumberValidator
    - ExEss\Cms\Validators\UserIdValidator
    - ExEss\Cms\Validators\VatValidator

services:
  _defaults:
    public: true

  Symfony\Component\Validator\Validator\ValidatorInterface:
    class: Symfony\Component\Validator\Validator\ValidatorInterface
    factory: ['ExEss\Cms\Factory\ValidatorFactory', create]
    arguments:
      - '@service_container'

  ExEss\Cms\Api\V8_Custom\Params\Validator\ValidatorFactory:
    lazy: true
    class: ExEss\Cms\Api\V8_Custom\Params\Validator\ValidatorFactory
    arguments:
      - '@Symfony\Component\Validator\Validator\ValidatorInterface'

  # Validators
  ExEss\Cms\Validators\FixedPhoneNumberValidator:
    arguments:
      - '%default_country_code%'
      - '@libphonenumber\PhoneNumberUtil'

  ExEss\Cms\Validators\InListValidator: ~
  ExEss\Cms\Validators\IsEndOfMonthValidator: ~

  ExEss\Cms\Validators\MobilePhoneNumberValidator:
    arguments:
      - '%default_country_code%'
      - '@libphonenumber\PhoneNumberUtil'

  ExEss\Cms\Validators\MultiEmailValidator: ~
  ExEss\Cms\Validators\NotInListValidator: ~

  ExEss\Cms\Validators\PhoneNumberValidator:
    arguments:
      - '%default_country_code%'
      - '@libphonenumber\PhoneNumberUtil'

  ExEss\Cms\Validators\UserIdValidator:
    arguments:
      - '@doctrine.orm.entity_manager'

  ExEss\Cms\Validators\VatValidator:
    arguments:
      - '@ExEss\Cms\FieldFormatter\VatNumberFormatter'

  # Factories
  ExEss\Cms\Validators\Factory\ConstraintValidatorFactory:
    arguments:
      - '@service_container'
      - '%validators%'

  ExEss\Cms\Validators\Factory\ConstraintFactory:
    arguments:
      - '%constraints%'
