monolog:
  channels:
    - !php/const \ExEss\Bundle\CmsBundle\Logger\Logger::CHANNEL_DEFAULT
    - !php/const \ExEss\Bundle\CmsBundle\Logger\Logger::CHANNEL_AUTHENTICATION
    - !php/const \ExEss\Bundle\CmsBundle\Logger\Logger::CHANNEL_REQUEST
    - 'client-request'
    - 'client-response'
    - 'client-exception'