#
# Internal API clients
#
# Internal meaning any service that is IN our infrastructure, which should never use a proxy
#
parameters:
  env(LOCAL_PROXY_HOST): null
  env(LOCAL_PROXY_PORT): null

services:
  _defaults:
    public: true

  ExEss\Bundle\CmsBundle\Component\Client\Serializer\Normalizer\GuzzleResponseNormalizer:
    tags: ['serializer.normalizer']

  ExEss\Bundle\CmsBundle\Component\Client\Event\Listeners\EnhanceHeadersSubscriber:
    autowire: true
    tags: [{ name: 'crm.subscriber', key: 'ExEss\Bundle\CmsBundle\Component\Client\Event\Listeners\EnhanceHeadersSubscriber' }]

  ExEss\Bundle\CmsBundle\Component\Client\Event\Listeners\LogSubscriber:
    autowire: true
    tags: [{ name: 'crm.subscriber', key: 'ExEss\Bundle\CmsBundle\Component\Client\Event\Listeners\LogSubscriber' }]
