services:
  _defaults:
    public: true

  ExEss\Bundle\CmsBundle\Api\V8_Custom\Repository\ListHandler:
    arguments:
      - !tagged { tag: 'handler.list', index_by: 'alias' }
      - '@ExEss\Bundle\CmsBundle\Api\V8_Custom\Service\FlashMessages\FlashMessageContainer'

  ExEss\Bundle\CmsBundle\Servicemix\ExternalObjectHandler:
    arguments:
      - !tagged { tag: 'handler.flow', index_by: 'alias' }
      - '@ExEss\Bundle\CmsBundle\Api\V8_Custom\Service\FlashMessages\FlashMessageContainer'
      - '@ExEss\Bundle\CmsBundle\Logger\Logger'

imports:
  - { resource: 'handlers/aftersave.yaml' }
  - { resource: 'handlers/response.yaml' }
  - { resource: 'handlers/save.yaml' }
