parameters:
    env(LOGGER_TAG): 'local.crm'
    logger_tag: '%env(string:LOGGER_TAG)%'

services:
#    monolog.formatter.dashed:
#        class: Monolog\Formatter\LineFormatter
#        arguments:
#            - !php/const ExEss\Bundle\CmsBundle\Logger\Logger::LOGGER
#            - "Y-m-d H:i:s.u"

    Monolog\Processor\WebProcessor:
      class: Monolog\Processor\WebProcessor
      tags:
        - { name: monolog.processor }

    Monolog\Processor\ProcessIdProcessor:
        class: Monolog\Processor\ProcessIdProcessor
        tags:
            - { name: monolog.processor }

    ExEss\Bundle\CmsBundle\Component\Logger\Processor\EnvironmentProcessor:
        arguments:  ['%logger_tag%']
        tags:
            - { name: monolog.processor }

    ExEss\Bundle\CmsBundle\Logger\Processor\NeededHeadersProcessor:
        arguments:
            - '@ExEss\Bundle\CmsBundle\Component\Session\Headers'
            - '@ExEss\Bundle\CmsBundle\Api\V8_Custom\Service\Security'
        tags:
            - { name: monolog.processor }

    ExEss\Bundle\CmsBundle\Component\Logger\Processor\XLogIdProcessor:
        arguments:  ['@ExEss\Bundle\CmsBundle\Component\Session\Headers']
        tags:
            - { name: monolog.processor }
