services:
  _defaults:
    public: true

  ExEss\Bundle\CmsBundle\Api\V8_Custom\Repository\RelationsRepository:
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@ExEss\Bundle\CmsBundle\Service\FilterService'
    tags: [{ name: 'handler.list', alias: 'relationsHandler' }]

  # External repositories
  ExEss\Bundle\CmsBundle\Api\V8_Custom\Repository\AuditRepository:
    arguments:
      - '@doctrine.orm.entity_manager'
    tags: [{ name: 'handler.list', alias: 'auditHandler' }]

  ExEss\Bundle\CmsBundle\Api\V8_Custom\Repository\ExternalObjectRepository:
    arguments:
      - '@ExEss\Bundle\CmsBundle\Servicemix\ExternalObjectHandler'
      - '@ExEss\Bundle\CmsBundle\Api\V8_Custom\Repository\ListHandler'
      - '@ExEss\Bundle\CmsBundle\Component\ExpressionParser\ParserService'

  # Crud related repositories
  ExEss\Bundle\CmsBundle\CRUD\Handlers\CrudAllBeansRepository:
    arguments:
      - '@ExEss\Bundle\CmsBundle\CRUD\Helpers\SecurityService'
    tags: [ { name: 'handler.list', alias: 'CrudAllBeansHandler' } ]

  ExEss\Bundle\CmsBundle\CRUD\Handlers\CrudRecordsRepository:
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@ExEss\Bundle\CmsBundle\Service\FilterService'
      - '@ExEss\Bundle\CmsBundle\CRUD\Helpers\SecurityService'
    tags:
      - { name: 'handler.list', alias: 'CrudRecordsRepository' }
      - { name: 'handler.flow', alias: 'CrudRecordsRepository' }

  ExEss\Bundle\CmsBundle\CRUD\Handlers\CrudRecordRelationsRepository:
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@ExEss\Bundle\CmsBundle\Service\FilterService'
    tags:
      - { name: 'handler.list', alias: 'CrudRecordRelationsRepository' }
      - { name: 'handler.flow', alias: 'CrudRecordRelationsRepository' }

  ExEss\Bundle\CmsBundle\CRUD\Handlers\CrudSelectRelationsRepository:
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@ExEss\Bundle\CmsBundle\Service\FilterService'
    tags: [{ name: 'handler.list', alias: 'CrudSelectRelationsRepository' }]

