#parameters:
#  app_secret: '%env(string:APP_SECRET)%'
#  api_token_timeout: 3600

services:
  _defaults:
    public: true
    autowire: true

#  ExEss\Bundle\CmsBundle\Api\V8_Custom\Service\User\TokenService:
#    bind:
#      $timeout: '%api_token_timeout%'
#      $secret: '%app_secret%'

#  ExEss\Bundle\CmsBundle\Security\JsonLoginAuthenticator: ~
#
#  ExEss\Bundle\CmsBundle\Security\JwtTokenAuthenticator: ~

  ExEss\Bundle\CmsBundle\Security\Listener\LogoutSuccessSubscriber:
    tags:
      - name: kernel.event_subscriber
        dispatcher: security.event_dispatcher.api

  ExEss\Bundle\CmsBundle\Api\V8_Custom\Service\User\DefaultUser: ~

  ExEss\Bundle\CmsBundle\Acl\AclService: ~

  ExEss\Bundle\CmsBundle\Users\Security\DecisionManager:
    bind:
      $voters: !tagged_iterator user.voter

  ExEss\Bundle\CmsBundle\Security\Route\DecisionManager:
    bind:
      $voters: !tagged_iterator route.voter

  # Route voters

  ExEss\Bundle\CmsBundle\Security\Route\Voter\RouteVoter:
    autowire: true
    tags: ['route.voter']

  # CRUD

  ExEss\Bundle\CmsBundle\CRUD\Helpers\SecurityService: ~
