parameters:
  env(DEFAULT_PERMISSIONS_DIR_MODE): null
  env(DEFAULT_PERMISSIONS_FILE_MODE): null
  env(CONFIG_CACHE_CACHE): false

  env_name: '%env(string:ENV_NAME)%'
  env_type: '%env(string:ENV_TYPE)%'
  env_url: '%env(string:ENV_URL)%'
  max_upload_file_size_mb: 5
  config_cache: '%env(bool:CONFIG_CACHE_CACHE)%'

services:
  _defaults:
    public: true
    bind:
      $fallbackLocale: '%default_locale%'
      $siteUrl: '%env_url%'
      $debug: '%verbose_errors%'
      $requestLogger: '@monolog.logger.request'

  ExEss\Bundle\CmsBundle\Component\Session\Headers:
    factory: [ 'ExEss\Bundle\CmsBundle\Component\Session\Headers', 'create' ]

  ExEss\Bundle\CmsBundle\Logger\Logger:
    arguments:
      - '@monolog.logger'

  ExEss\Bundle\CmsBundle\Api\V8_Custom\Service\FlashMessages\FlashMessageContainer:
    lazy: true
    factory: [ExEss\Bundle\CmsBundle\Api\V8_Custom\Service\FlashMessages\FlashMessageContainer, get]

  Symfony\Component\EventDispatcher\EventDispatcher:
    factory: [ExEss\Bundle\CmsBundle\Api\V8_Custom\Service\EventDispatcherFactory, getEventDispatcher]
    arguments:
      - '@service_container'
      - !tagged { tag: 'crm.subscriber', index_by: 'key' }

  Symfony\Component\EventDispatcher\EventDispatcherInterface: '@Symfony\Component\EventDispatcher\EventDispatcher'
  event_dispatcher: '@Symfony\Component\EventDispatcher\EventDispatcher'

  ExEss\Bundle\CmsBundle\Component\Flow\Event\FlowEventDispatcher:
    autowire: true

  ExEss\Bundle\CmsBundle\Component\Flow\Validator:
    lazy: true
    arguments:
      - '@Symfony\Component\Validator\Validator\ValidatorInterface'
      - '@ExEss\Bundle\CmsBundle\Validators\Factory\ConstraintFactory'
      - '@ExEss\Bundle\CmsBundle\Logger\Logger'
      - '@ExEss\Bundle\CmsBundle\Component\ExpressionParser\ParserService'
      - '@Symfony\Component\Translation\Translator'
      - '@ExEss\Bundle\CmsBundle\Api\V8_Custom\Service\FlashMessages\FlashMessageContainer'

  ExEss\Bundle\CmsBundle\Component\Flow\FlowValidator:
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@ExEss\Bundle\CmsBundle\Component\Flow\Validator'
      - '@ExEss\Bundle\CmsBundle\Service\GridService'

  ExEss\Bundle\CmsBundle\Component\Health\PingService: ~

  ExEss\Bundle\CmsBundle\Config\Cache\ConfigCacheFactory:
    arguments:
      - '%config_cache%'
      - '@=service(constant("ExEss\\Bundle\\CmsBundle\\Component\\Cache\\Dictionary::CONFIG"))'
      - '@ExEss\Bundle\CmsBundle\Component\ExpressionParser\ParserService'
      - '@ExEss\Bundle\CmsBundle\Api\V8_Custom\Service\Security'

  ExEss\Bundle\CmsBundle\Users\Service\GuidanceRecoveryService:
    arguments:
      - '@ExEss\Bundle\CmsBundle\Api\V8_Custom\Service\Security'
      - '@doctrine.orm.entity_manager'

  ExEss\Bundle\CmsBundle\Api\V8_Custom\Service\Security:
    lazy: true
    arguments:
      - '@security.token_storage'
      - '%default_locale%'

  ExEss\Bundle\CmsBundle\Component\Flow\DefaultValueService:
    arguments:
      - '@ExEss\Bundle\CmsBundle\MultiLevelTemplate\TextFunctionHandler'

  ExEss\Bundle\CmsBundle\Cleaner\HtmlCleaner:
    arguments:
      - '%env_url%'
      - '%kernel.cache_dir%/htmlcleaner'

  JsonMapper:
    class: JsonMapper
    factory: [ExEss\Bundle\CmsBundle\Factory\JsonMapperFactory, create]

  ExEss\Bundle\CmsBundle\Component\Flow\Builder\FormBuilder:
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@ExEss\Bundle\CmsBundle\Component\Flow\Builder\EnumFieldBuilder'
      - '@ExEss\Bundle\CmsBundle\Component\ExpressionParser\ParserService'
      - '@ExEss\Bundle\CmsBundle\Service\SelectWithSearchService'
      - '@Symfony\Component\Translation\Translator'
      - '@ExEss\Bundle\CmsBundle\Api\V8_Custom\Service\Security'
      - '@ExEss\Bundle\CmsBundle\Component\Flow\Field'

  ExEss\Bundle\CmsBundle\Component\Flow\Field:
    arguments:
      - '%max_upload_file_size_mb%'

  ExEss\Bundle\CmsBundle\Component\Flow\Builder\EnumFieldBuilder:
    lazy: true
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@ExEss\Bundle\CmsBundle\Logger\Logger'
      - '@ExEss\Bundle\CmsBundle\Api\V8_Custom\Repository\ListHandler'
      - '@ExEss\Bundle\CmsBundle\Component\Flow\EnumRecordFactory'
      - '@ExEss\Bundle\CmsBundle\Service\SelectWithSearchService'

  ExEss\Bundle\CmsBundle\Component\Sidebar\Factory\SidebarFactory: ~

  ExEss\Bundle\CmsBundle\Api\V8_Custom\Service\User\CommandService:
    arguments:
      - '@ExEss\Bundle\CmsBundle\Users\Service\GuidanceRecoveryService'

  ExEss\Bundle\CmsBundle\FieldFormatter\VatNumberFormatter: ~

  libphonenumber\PhoneNumberUtil:
    class: libphonenumber\PhoneNumberUtil
    factory: [libphonenumber\PhoneNumberUtil, getInstance]

  ExEss\Bundle\CmsBundle\FieldFormatter\PhoneNumberFormatter:
    arguments:
      - 'BE'
      - '@libphonenumber\PhoneNumberUtil'

  ExEss\Bundle\CmsBundle\FieldFormatter\IbanFormatter: ~

  ExEss\Bundle\CmsBundle\Api\V8_Custom\Service\SimpleActionFactory:
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@ExEss\Bundle\CmsBundle\Logger\Logger'

  ExEss\Bundle\CmsBundle\Component\Flow\ActionFactory:
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@ExEss\Bundle\CmsBundle\Component\Flow\Event\FlowEventDispatcher'
      - '@ExEss\Bundle\CmsBundle\Logger\Logger'
      - '@Symfony\Component\Translation\Translator'

  ExEss\Bundle\CmsBundle\Component\Flow\EnumRecordFactory:
    arguments:
      - '@Symfony\Component\Translation\Translator'
      - '@ExEss\Bundle\CmsBundle\Api\V8_Custom\Service\Security'

  ExEss\Bundle\CmsBundle\MultiLevelTemplate\TextFunctionHandler:
    arguments:
      - '@ExEss\Bundle\CmsBundle\Logger\Logger'
      - '@Symfony\Component\Translation\Translator'

  ExEss\Bundle\CmsBundle\Http\Factory\PsrFactory: ~

  ExEss\Bundle\CmsBundle\Http\Factory\JsonBodyFactory:
    autowire: true

  # Autowired Service and Controller directory
  ExEss\Bundle\CmsBundle\Service\:
    public: true
    autowire: true
    resource: "Service/"

  ExEss\Bundle\CmsBundle\Controller\:
    public: true
    autowire: true
    resource: "Controller/"

  ExEss\Bundle\CmsBundle\Command\:
    public: true
    autowire: true
    autoconfigure: true
    parent: ExEss\Bundle\CmsBundle\Command\AbstractAdminCommand
    resource: "Command/"

  ExEss\Bundle\CmsBundle\Component\PhpCS\Command\:
    public: true
    autowire: true
    autoconfigure: true
    resource: "Component/PhpCS/Command/"

  ExEss\Bundle\CmsBundle\Repository\:
    autowire: true
    autoconfigure: true
    resource: "Repository/"

  ExEss\Bundle\CmsBundle\Http\EventSubscriber\:
    autowire: true
    autoconfigure: true
    resource: "Http/EventSubscriber"

imports:
  - { resource: 'api_client_external.yaml' }
  - { resource: 'api_client_internal.yaml' }
  - { resource: 'backendCommands.yaml' }
  - { resource: 'commands.yaml' }
  - { resource: 'converters.yaml' }
  - { resource: 'database.yaml' }
  - { resource: 'handlers.yaml' }
  - { resource: 'health.yaml' }
  - { resource: 'logging.yaml' }
  - { resource: 'repositories.yaml' }
  - { resource: 'security.yaml' }
  - { resource: 'subscribers.yaml' }
  - { resource: 'suggestions.yaml' }
  - { resource: 'translators.yaml' }
  - { resource: 'validation.yaml' }
  - { resource: 'entity_listeners.yaml' }
  - { resource: 'component/expression_parser.yaml' }
  - { resource: 'component/cache.yaml' }
