parameters:
  env(VERBOSE_ERRORS): false
  verbose_errors: '%env(bool:VERBOSE_ERRORS)%'

services:
  _defaults:
    public: true

  ExEss\Bundle\CmsBundle\Api\V8_Custom\Events\Listeners\EnhanceHeadersSubscriber:
    lazy: true
    arguments:
      - '@ExEss\Bundle\CmsBundle\Api\V8_Custom\Service\Security'
    tags: [{ name: 'crm.subscriber', key: 'ExEss\Bundle\CmsBundle\Api\V8_Custom\Events\Listeners\EnhanceHeadersSubscriber' }]

  ExEss\Bundle\CmsBundle\Api\V8_Custom\Events\Listeners\ExternalApiLogSubscriber:
    lazy: true
    arguments:
      - '@ExEss\Bundle\CmsBundle\Logger\Logger'
    tags: [{ name: 'crm.subscriber', key: 'ExEss\Bundle\CmsBundle\Api\V8_Custom\Events\Listeners\ExternalApiLogSubscriber' }]

  ExEss\Bundle\CmsBundle\Api\V8_Custom\Events\Listeners\UpdateLastLoginSubscriber:
    lazy: true
    arguments:
      - '@doctrine.orm.entity_manager'
    tags: [{ name: 'crm.subscriber', key: 'ExEss\Bundle\CmsBundle\Api\V8_Custom\Events\Listeners\UpdateLastLoginSubscriber' }]

  ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\PreValidationSubscriber:
    lazy: true
    arguments:
      - '@service_container'
      - !tagged_iterator pre-validation-suggestion
      - '@doctrine.orm.entity_manager'
      - '@ExEss\Bundle\CmsBundle\Service\GridService'
    tags: [{ name: 'crm.subscriber', key: 'ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\PreValidationSubscriber' }]

  ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\SuggestionsSubscriber:
    lazy: true
    arguments:
      - '@ExEss\Bundle\CmsBundle\Component\Flow\Event\FlowEventDispatcher'
      - '@service_container'
      - !tagged_iterator suggestions
    tags: [{ name: 'crm.subscriber', key: 'ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\SuggestionsSubscriber' }]

  ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\ResponseHandlerSubscriber:
    lazy: true
    arguments:
      $container: '@service_container'
    tags: [{ name: 'crm.subscriber', key: 'ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\ResponseHandlerSubscriber' }]

  ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\PreDispatchSubscriber:
    lazy: true
    arguments:
      - '@doctrine.orm.entity_manager'
    tags: [{ name: 'crm.subscriber', key: 'ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\PreDispatchSubscriber' }]

  ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\RecordIdSubscriber:
    lazy: true
    arguments:
      - '@doctrine.orm.entity_manager'
    tags: [{ name: 'crm.subscriber', key: 'ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\RecordIdSubscriber' }]

  ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\GuidanceSubscriber:
    lazy: true
    tags: [{ name: 'crm.subscriber', key: 'ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\GuidanceSubscriber' }]


  ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\NextStepSubscriber:
    lazy: true
    tags: [{ name: 'crm.subscriber', key: 'ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\NextStepSubscriber' }]

  ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\ProgressSubscriber:
    lazy: true
    arguments:
      - '@Symfony\Component\Translation\Translator'
    tags: [{ name: 'crm.subscriber', key: 'ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\ProgressSubscriber' }]

  ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\ExternalFlowSubscriber:
    lazy: true
    arguments:
      - '@ExEss\Bundle\CmsBundle\Servicemix\ExternalObjectHandler'
    tags: [{ name: 'crm.subscriber', key: 'ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\ExternalFlowSubscriber' }]

  ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\BaseEntitySubscriber:
    lazy: true
    arguments:
      - '@doctrine.orm.entity_manager'
    tags: [{ name: 'crm.subscriber', key: 'ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\BaseEntitySubscriber' }]

  ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\ValidationSubscriber:
    lazy: true
    arguments:
      - '@ExEss\Bundle\CmsBundle\Component\Flow\FlowValidator'
      - '@ExEss\Bundle\CmsBundle\Component\Flow\ActionFactory'
      - '@ExEss\Bundle\CmsBundle\Component\Flow\Builder\FormBuilder'
      - '@ExEss\Bundle\CmsBundle\Api\V8_Custom\Service\FlashMessages\FlashMessageContainer'
    tags: [{ name: 'crm.subscriber', key: 'ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\ValidationSubscriber' }]

  ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\ChildModelSubscriber:
    lazy: true
    arguments:
      - '@ExEss\Bundle\CmsBundle\Service\GridService'
      - '@ExEss\Bundle\CmsBundle\Component\Flow\Event\FlowEventDispatcher'
    tags: [{ name: 'crm.subscriber', key: 'ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\ChildModelSubscriber' }]

  ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\GridSubscriber:
    lazy: true
    arguments:
      - '@ExEss\Bundle\CmsBundle\Service\GridService'
    tags: [{ name: 'crm.subscriber', key: 'ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\GridSubscriber' }]

  ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\FormAndModelSubscriber:
    lazy: true
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@ExEss\Bundle\CmsBundle\Component\Flow\Builder\FormBuilder'
      - '@ExEss\Bundle\CmsBundle\Component\Flow\DefaultValueService'
      - '@ExEss\Bundle\CmsBundle\Service\GridService'
      - '@ExEss\Bundle\CmsBundle\Logger\Logger'
    tags: [{ name: 'crm.subscriber', key: 'ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\FormAndModelSubscriber' }]

  ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\ValueExpressionsSubscriber:
    lazy: true
    arguments:
      - '@ExEss\Bundle\CmsBundle\MultiLevelTemplate\TextFunctionHandler'
      - '@ExEss\Bundle\CmsBundle\Api\V8_Custom\Service\FlashMessages\FlashMessageContainer'
      - '@ExEss\Bundle\CmsBundle\Component\ExpressionParser\ParserService'
      - '@ExEss\Bundle\CmsBundle\Service\SelectWithSearchService'
    tags: [{ name: 'crm.subscriber', key: 'ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\ValueExpressionsSubscriber' }]

  ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\BreakoutSubscriber:
    lazy: true
    arguments:
      - '@ExEss\Bundle\CmsBundle\Service\RepeatableRowService'
      - '@ExEss\Bundle\CmsBundle\Component\Flow\Event\FlowEventDispatcher'
    tags: [{ name: 'crm.subscriber', key: 'ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\BreakoutSubscriber' }]

  ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\SaveSubscriber:
    lazy: true
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@ExEss\Bundle\CmsBundle\Service\GridService'
      - '@ExEss\Bundle\CmsBundle\Component\Flow\SaveFlow'
      - '@ExEss\Bundle\CmsBundle\Component\Flow\MultiLineFlowSaver'
      - '@ExEss\Bundle\CmsBundle\Component\Flow\ActionFactory'
      - '@ExEss\Bundle\CmsBundle\Component\Flow\AfterSave\Handler\AfterSaveHandlerQueue'
      - '@ExEss\Bundle\CmsBundle\Component\Flow\Builder\FormBuilder'
    tags: [{ name: 'crm.subscriber', key: 'ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\SaveSubscriber' }]

  ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\ModelCleanerSubscriber:
    lazy: true
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@ExEss\Bundle\CmsBundle\Component\Flow\Builder\FormBuilder'
      - '@ExEss\Bundle\CmsBundle\Service\GridService'
      - '@ExEss\Bundle\CmsBundle\Logger\Logger'
    tags: [{ name: 'crm.subscriber', key: 'ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\ModelCleanerSubscriber' }]

  ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\GuidanceRecoverySubscriber:
    lazy: true
    arguments:
      - '@ExEss\Bundle\CmsBundle\Users\Service\GuidanceRecoveryService'
    tags: [{ name: 'crm.subscriber', key: 'ExEss\Bundle\CmsBundle\Component\Flow\Event\Listeners\GuidanceRecoverySubscriber' }]
