migration_base_class: ExEss\Cms\Robo\AbstractMigration

paths:
    migrations:
        - '%%PHINX_CONFIG_DIR%%/../dev/database/migrations'
    seeds: '%%PHINX_CONFIG_DIR%%/../dev/database/seeds'

environments:
    default_migration_table: phinxlog
    default_database: '%%PHINX_DB_NAME%%'
    default:
        adapter: mysql
        host: '%%PHINX_DB_HOST_NAME%%'
        name: '%%PHINX_DB_NAME%%'
        user: '%%PHINX_DB_USER_NAME%%'
        pass: '%%PHINX_DB_PASSWORD%%'
        charset: utf8
