services:
  _defaults:
    autowire: true
    autoconfigure: true

  ExEss\Cms\DependencyInjection\ServicesResetter:
    arguments:
      - !tagged_iterator crm.reset

  ExEss\Cms\Controller\:
    public: true
    autowire: true
    resource: '../src/ExEss/Cms/Controller/'

imports:
  - { resource: 'services/services.yaml' }