services:
  _defaults:
    autowire: true
    autoconfigure: true

  ExEss\Cms\Controller\:
    public: true
    autowire: true
    resource: '../src/ExEss/Cms/Controller/'

imports:
  - { resource: 'services/services.yaml' }