services:
  _defaults:
    autowire: true
    autoconfigure: true

  ExEss\Cms\DependencyInjection\ServicesResetter:
    arguments:
      - !tagged_iterator crm.reset

  ExEss\Cms\App:
    public: true
    arguments:
      - '@service_container'
      - '@ExEss\Cms\Loader\MiddlewareLoader'

  ExEss\Cms\Controller\:
    public: true
    autowire: true
    resource: '../src/ExEss/Cms/Controller/'

imports:
  - { resource: 'services/services.yaml' }