services:
  _defaults:
    autowire: true
    autoconfigure: true

  ExEss\Bundle\CmsBundle\Controller\:
    public: true
    autowire: true
    resource: '../src/ExEss/Bundle/CmsBundle/Controller/'

imports:
  - { resource: 'services/services.yaml' }