parameters:
  routerCacheFile: false

services:
  _defaults:
    public: true

  test.monolog.logger: '@monolog.logger'

  Helper\TestRepository:
    tags: [{ name: 'handler.list', alias: !php/const Helper\TestRepository::NAME }]

