services:
  ExEss\Bundle\DoctrineExtensionsBundle\Event\Subscriber\AuditSubscriber:
    arguments:
      - '@Doctrine\Common\Annotations\Reader'
    tags: ['kernel.event_subscriber']  

  ExEss\Bundle\DoctrineExtensionsBundle\Event\Subscriber\LargeEnumTypeSubscriber: 
    tags: ['kernel.event_subscriber']  
  
  ExEss\Bundle\DoctrineExtensionsBundle\Provider\SchemaTool: 
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@event_dispatcher'
  
  ExEss\Bundle\DoctrineExtensionsBundle\Provider\SchemaProvider:
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@ExEss\Bundle\DoctrineExtensionsBundle\Provider\SchemaTool'

  ExEss\Bundle\DoctrineExtensionsBundle\Factory\DependencyFactory:
    class: Doctrine\Migrations\DependencyFactory
    factory: ['ExEss\Bundle\DoctrineExtensionsBundle\Factory\DependencyFactory', 'fromEntityManager']
    arguments:
      - '@doctrine.migrations.configuration_loader'
      - '@doctrine.migrations.entity_manager_registry_loader'
      - '@ExEss\Bundle\DoctrineExtensionsBundle\Provider\SchemaProvider'
      - '@logger'
