services:
  _defaults:
    public: true
    autowire: true

  ExEss\Bundle\CmsBundle\Component\ExpressionParser\Parser\Translator\EntityTranslator: ~
  ExEss\Bundle\CmsBundle\Component\ExpressionParser\Parser\Translator\QueryTranslator: ~

  ExEss\Bundle\CmsBundle\Component\ExpressionParser\Parser\PathResolver:
    bind:
      $translators:
        ExEss\Bundle\CmsBundle\Component\ExpressionParser\Parser\Translator\EntityTranslator: '@ExEss\Bundle\CmsBundle\Component\ExpressionParser\Parser\Translator\EntityTranslator'
        ExEss\Bundle\CmsBundle\Component\ExpressionParser\Parser\Translator\QueryTranslator: '@ExEss\Bundle\CmsBundle\Component\ExpressionParser\Parser\Translator\QueryTranslator'

  ExEss\Bundle\CmsBundle\Component\ExpressionParser\Parser\ExpressionGroupParser: ~
  ExEss\Bundle\CmsBundle\Component\ExpressionParser\Parser\ExpressionParser: ~

  ExEss\Bundle\CmsBundle\Component\ExpressionParser\Parser\PathCompiler:
    bind:
      $cache: '@=service(constant("ExEss\\Bundle\\CmsBundle\\Component\\Cache\\Dictionary::COMPILER_PATHS"))'

  ExEss\Bundle\CmsBundle\Component\ExpressionParser\Parser\Compiler\ExternalObjectCompiler: ~
  ExEss\Bundle\CmsBundle\Component\ExpressionParser\Parser\Compiler\ObjectMethodCompiler: ~
  ExEss\Bundle\CmsBundle\Component\ExpressionParser\Parser\Compiler\ObjectPropertyCompiler: ~
  ExEss\Bundle\CmsBundle\Component\ExpressionParser\Parser\Compiler\AssociationCompiler: ~
  ExEss\Bundle\CmsBundle\Component\ExpressionParser\Parser\Compiler\ExternalLinkCompiler: ~
  ExEss\Bundle\CmsBundle\Component\ExpressionParser\Parser\Compiler\DateTimeCompiler: ~
  ExEss\Bundle\CmsBundle\Component\ExpressionParser\Parser\Compiler\SecurityCompiler: ~
  ExEss\Bundle\CmsBundle\Component\ExpressionParser\Parser\Compiler\RelationListCompiler: ~

  ExEss\Bundle\CmsBundle\Component\ExpressionParser\ParserService:
    bind:
      $cache: '@=service(constant("ExEss\\Bundle\\CmsBundle\\Component\\Cache\\Dictionary::PARSED_QUERY_USER"))'

